export const topics = [
  "export",
  "growth",
  "oil",
  "gas",
  "fracking",
  "war",
  "energy",
  "coal",
  "security",
  "money",
  "car",
  "pollution",
  "economy",
  "unemployment",
  "market",
  "Washington",
  "production",
  "material",
  "gdp",
  "investment",
  "government",
  "consumer",
  "robot",
  "biofuel",
];

export const sector = [
  "Retail",
  "Manufacturing",
  "Financial services",
  "Energy",
  "Environment",
  "Support services",
  "Government",
  "Information Technology",
  "Media & entertainment",
  "Aerospace & defence",
  "Water",
  "Food & Agriculture",
  "Security",
  "Transport",
  "Healthcare",
  "Construction",
  "Automotive",
  "Tourism & hospitality",
];

export const region = [
  "World",
  "Northern America",
  "Eastern Europe",
  "Central America",
  "Western Asia",
  "Southern Asia",
  "Europe",
  "Western Africa",
  "Asia",
  "South-Eastern Asia",
  "Eastern Asia",
  "Oceania",
  "Northern Africa",
  "Southern Europe",
  "Northern Europe",
  "South America",
  "Western Europe",
  "Africa",
  "Central Africa",
  "Central Asia",
  "Eastern Africa",
  "Southern Africa",
];

export const pestle = [
  "Economic",
  "Environmental",
  "Social",
  "Industries",
  "Political",
  "Technological",
  "Organization",
  "Healthcare",
  "Lifestyles",
];

export const source = [
  "Wikipedia",
  "Bloomberg Business",
  "CNBC ",
  "Engineering News",
  "IHS Engineering 360",
  "Europe in My Region",
  "Rigzone",
  "CNNMoney",
  "Foreign Policy",
  "UNEP",
  "Imeche",
  "McKinsey & Company",
  "energy news cyprus",
  "uschamber",
  "Infracircle",
  "Oil & Gas Journal",
  "Face2face Africa",
  "The American Prospect",
  "Washington Post",
  "marketrealist",
  "EPS News",
  "dailytexanonline",
  "Australian Government",
  "conferenceseries",
  "greenerearthnews",
];

export const country = [
  "USA",
  "Poland",
  "Belize",
  "Cyprus",
  "India",
  "Nigeria",
  "Canada",
  "Indonesia",
  "Iraq",
  "Syria",
  "China",
  "Libya",
  "Iran",
  "Egypt",
  "Ghana",
  "Mexico",
  "UK",
  "Russia",
  "Turkey",
  "Japan",
  "Venezuela",
  "Algeria",
  "Saudi Arabia",
  "Jordan",
];
